apiVersion: v1
kind: Service
metadata:
  name: platform-ingest
  labels:
    app: platform-ingest
spec:
  selector:
    app: platform-ingest
  ports:
    - name: http
      port: 8081
      targetPort: http
