pipeline:
  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:debug
      commands:
        - /kaniko/executor --context=dir:///workspace --dockerfile=/workspace/Dockerfile --destination=$REGISTRY/$PROJECT/app:$COMMIT_SHA --insecure --cache=true

  dev_image:
    dockerfile: Dockerfile.dev
