DROP TABLE IF EXISTS metric_samples CASCADE;
DROP TABLE IF EXISTS metric_series CASCADE;
DROP TABLE IF EXISTS log_entries CASCADE;
DROP TABLE IF EXISTS spans CASCADE;
DROP TABLE IF EXISTS traces CASCADE;
