#!/usr/bin/env bash
# dev-env.sh — Deploy isolated dev services into Kind using NodePort (no port-forwards).
#
# Each worktree gets its own K8s namespace (platform-dev-{worktree}) with auto-assigned
# NodePorts. Generates .env.dev with discovered ports. No port-forwards needed — direct
# Kind node IP access (OrbStack makes it routable on macOS).
#
# Workflow:
#   1. just cluster-up   # create Kind cluster (one-time)
#   2. just dev-env       # this script: deploy services, generate .env.dev
#   3. just run           # cargo run (loads .env.dev automatically)
#
# To stop:  just dev-env-stop
# To stop all worktrees:  just dev-env-stop-all

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
KIND_CLUSTER="platform"
NODE="${KIND_CLUSTER}-control-plane"

export KUBECONFIG="${HOME}/.kube/kind-${KIND_CLUSTER}"

# ── Pre-flight checks ────────────────────────────────────────────────────
if ! kind get clusters 2>/dev/null | grep -q "^${KIND_CLUSTER}$"; then
  echo "ERROR: Kind cluster '${KIND_CLUSTER}' not found. Run: just cluster-up"
  exit 1
fi

# Refresh kubeconfig (API server port changes on cluster recreate)
kind get kubeconfig --name "$KIND_CLUSTER" > "$KUBECONFIG"
KUBECONFIG="${HOME}/.kube/config" kind export kubeconfig --name "$KIND_CLUSTER"

# ── Detect worktree name ─────────────────────────────────────────────────
WORKTREE="$(bash "${SCRIPT_DIR}/detect-worktree.sh")"
NS="platform-dev-${WORKTREE}"

echo "==> Worktree: ${WORKTREE}"
echo "  Namespace: ${NS}"

# ── Get Kind node IP (OrbStack makes it routable from macOS) ─────────────
NODE_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "${NODE}")
if [[ -z "$NODE_IP" ]]; then
  echo "ERROR: Could not determine node IP for ${NODE}"
  exit 1
fi
echo "  Node IP:   ${NODE_IP}"

# ── Detect host address (for in-pod → host communication) ────────────────
if [[ "$(uname)" == "Darwin" ]]; then
  PLATFORM_HOST="host.docker.internal"
else
  PLATFORM_HOST=$(docker network inspect kind \
    -f '{{range .IPAM.Config}}{{.Gateway}}{{end}}' 2>/dev/null || echo "172.18.0.1")
fi

# ── Find free ports ──────────────────────────────────────────────────────
find_free_port() {
  python3 -c "import socket; s=socket.socket(); s.bind(('',0)); print(s.getsockname()[1]); s.close()"
}

find_free_node_port() {
  docker exec "${NODE}" \
    python3 -c "import socket; s=socket.socket(); s.bind(('',0)); print(s.getsockname()[1]); s.close()"
}

BACKEND_PORT=$(find_free_port)
REGISTRY_NODE_PORT=$(find_free_node_port)

echo ""
echo "==> Auto-assigned ports"
echo "  Backend:  ${BACKEND_PORT}"
echo "  Registry: ${REGISTRY_NODE_PORT} (node hostPort)"

# ── Deploy services + registry proxy (idempotent) ────────────────────────
REGISTRY_BACKEND_HOST="${PLATFORM_HOST}" \
  REGISTRY_BACKEND_PORT="${BACKEND_PORT}" \
  REGISTRY_NODE_PORT="${REGISTRY_NODE_PORT}" \
  bash "${SCRIPT_DIR}/deploy-services.sh" "${NS}"

# ── Discover NodePorts (K8s auto-assigned) ───────────────────────────────
echo ""
echo "==> Discovering NodePorts"
PG_PORT=$(kubectl get svc -n "${NS}" postgres -o jsonpath='{.spec.ports[0].nodePort}')
VALKEY_PORT=$(kubectl get svc -n "${NS}" valkey -o jsonpath='{.spec.ports[0].nodePort}')
MINIO_PORT=$(kubectl get svc -n "${NS}" minio -o jsonpath='{.spec.ports[0].nodePort}')
echo "  Postgres: ${NODE_IP}:${PG_PORT}"
echo "  Valkey:   ${NODE_IP}:${VALKEY_PORT}"
echo "  MinIO:    ${NODE_IP}:${MINIO_PORT}"

# Wait for NodePort connectivity (direct to Kind node — no port-forward)
echo -n "  Waiting for NodePort connectivity"
for i in $(seq 1 30); do
  if nc -z "$NODE_IP" "$PG_PORT" 2>/dev/null && \
     nc -z "$NODE_IP" "$VALKEY_PORT" 2>/dev/null && \
     nc -z "$NODE_IP" "$MINIO_PORT" 2>/dev/null; then
    break
  fi
  echo -n "."
  sleep 0.5
done
echo " ready"

# ── Generate .env.dev ────────────────────────────────────────────────────
ENV_FILE="${PROJECT_DIR}/.env.dev"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by hack/dev-env.sh — do not edit manually.
# Worktree: ${WORKTREE}  |  Namespace: ${NS}
# Re-run 'just dev-env' to regenerate.

# --- Data stores (NodePort via Kind node — no port-forwards) ---
DATABASE_URL=postgres://platform:dev@${NODE_IP}:${PG_PORT}/platform_dev
VALKEY_URL=redis://${NODE_IP}:${VALKEY_PORT}
MINIO_ENDPOINT=http://${NODE_IP}:${MINIO_PORT}
MINIO_ACCESS_KEY=platform
MINIO_SECRET_KEY=devdevdev

# --- Platform core ---
PLATFORM_LOG=debug
PLATFORM_LISTEN=0.0.0.0:${BACKEND_PORT}
PLATFORM_DEV=true

# AES-256-GCM key for secrets encryption (64 hex chars = 32 bytes)
PLATFORM_MASTER_KEY=0000000000000000000000000000000000000000000000000000000000000000

# --- Container registry ---
# for image pull (localhost auto-allows plain HTTP; NodePort of DaemonSet registry proxy)
PLATFORM_REGISTRY_NODE_URL=localhost:${REGISTRY_NODE_PORT}
# for push (Kaniko --destination prefix; no scheme — Kaniko adds it)
PLATFORM_REGISTRY_URL=${PLATFORM_HOST}:${BACKEND_PORT}

# --- Agent/Pipeline pod communication ---
PLATFORM_API_URL=http://${PLATFORM_HOST}:${BACKEND_PORT}
PLATFORM_VALKEY_AGENT_HOST=valkey.${NS}.svc.cluster.local:6379

# --- Namespace prefix (for per-project namespaces) ---
PLATFORM_NS_PREFIX=${NS}

# --- Storage paths ---
PLATFORM_GIT_REPOS_PATH=/tmp/platform-repos
PLATFORM_OPS_REPOS_PATH=/tmp/platform-ops-repos

# --- Seed images (OCI tarballs imported into registry on startup) ---
PLATFORM_SEED_IMAGES_PATH=/tmp/platform-e2e/seed-images

# --- Agent runner binaries (worktree-scoped to avoid cross-worktree overwrites) ---
PLATFORM_AGENT_RUNNER_DIR=/tmp/platform-e2e/${WORKTREE}/agent-runner

# --- K8s config ---
KUBECONFIG=${HOME}/.kube/kind-platform

# --- WebAuthn / Passkeys ---
WEBAUTHN_RP_ID=localhost
WEBAUTHN_RP_ORIGIN=http://localhost:${BACKEND_PORT}
WEBAUTHN_RP_NAME=Platform
EOF

# ── Summary ──────────────────────────────────────────────────────────────
echo ""
echo "==> Dev environment ready (${WORKTREE})"
echo "  Namespace:  ${NS}"
echo "  Postgres:   ${NODE_IP}:${PG_PORT}"
echo "  Valkey:     ${NODE_IP}:${VALKEY_PORT}"
echo "  MinIO:      ${NODE_IP}:${MINIO_PORT}"
echo "  Backend:    0.0.0.0:${BACKEND_PORT}"
echo "  Registry:   Kind node:${REGISTRY_NODE_PORT} → ${PLATFORM_HOST}:${BACKEND_PORT}"
echo "  .env.dev:   ${ENV_FILE}"
echo ""
echo "  Run: just run"
echo "  Stop: just dev-env-stop"
