#!/usr/bin/env bash
# dev-up.sh — Deploy isolated dev services into cluster using NodePort (no port-forwards).
#
# Each worktree gets its own K8s namespace (platform-dev-{worktree}) with auto-assigned
# NodePorts. Generates .env.dev with discovered ports. No port-forwards needed — direct
# cluster node IP access.
#
# Workflow:
#   1. just cluster-up   # create cluster (one-time)
#   2. just dev-up        # this script: deploy services, generate .env.dev
#   3. just dev           # cargo run (loads .env.dev automatically)
#
# To stop:  just dev-down
# To stop all worktrees:  just dev-down-all

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Cluster detection (k0s or Kind) ──────────────────────────────────────
source "${SCRIPT_DIR}/cluster-info.sh"

# ── Detect worktree name ─────────────────────────────────────────────────
WORKTREE="$(bash "${SCRIPT_DIR}/detect-worktree.sh")"
NS="platform-dev-${WORKTREE}"

echo "==> Worktree: ${WORKTREE}"
echo "  Namespace: ${NS}"
echo "  Cluster:   ${NODE_CONTAINER}"
echo "  Node IP:   ${NODE_IP}"

# ── Find free ports ──────────────────────────────────────────────────────
find_free_port() {
  python3 -c "import socket; s=socket.socket(); s.bind(('',0)); print(s.getsockname()[1]); s.close()"
}

BACKEND_PORT=$(find_free_port)
REGISTRY_NODE_PORT=$(find_free_node_port)
GATEWAY_HTTP_NODE_PORT=$(find_free_node_port)
GATEWAY_TLS_NODE_PORT=$(find_free_node_port)

echo ""
echo "==> Auto-assigned ports"
echo "  Backend:      ${BACKEND_PORT}"
echo "  Registry:     ${REGISTRY_NODE_PORT} (node hostPort)"
echo "  Gateway HTTP: ${GATEWAY_HTTP_NODE_PORT} (node hostPort)"
echo "  Gateway TLS:  ${GATEWAY_TLS_NODE_PORT} (node hostPort)"

# ── Deploy services + registry proxy (idempotent) ────────────────────────
REGISTRY_BACKEND_HOST="${PLATFORM_HOST}" \
  REGISTRY_BACKEND_PORT="${BACKEND_PORT}" \
  REGISTRY_NODE_PORT="${REGISTRY_NODE_PORT}" \
  bash "${SCRIPT_DIR}/deploy-services.sh" "${NS}"

# ── Discover NodePorts (K8s auto-assigned) ───────────────────────────────
echo ""
echo "==> Discovering NodePorts"
PG_PORT=$(kubectl get svc -n "${NS}" postgres -o jsonpath='{.spec.ports[0].nodePort}')
VALKEY_PORT=$(kubectl get svc -n "${NS}" valkey -o jsonpath='{.spec.ports[0].nodePort}')
MINIO_PORT=$(kubectl get svc -n "${NS}" minio -o jsonpath='{.spec.ports[0].nodePort}')
PREVIEW_PROXY_PORT=$(kubectl get svc -n "${NS}" preview-proxy -o jsonpath='{.spec.ports[0].nodePort}')
echo "  Postgres:      ${NODE_IP}:${PG_PORT}"
echo "  Valkey:        ${NODE_IP}:${VALKEY_PORT}"
echo "  MinIO:         ${NODE_IP}:${MINIO_PORT}"
echo "  Preview proxy: ${NODE_IP}:${PREVIEW_PROXY_PORT}"

# Wait for NodePort connectivity (direct to cluster node — no port-forward)
echo -n "  Waiting for NodePort connectivity"
for i in $(seq 1 30); do
  if nc -z "$NODE_IP" "$PG_PORT" 2>/dev/null && \
     nc -z "$NODE_IP" "$VALKEY_PORT" 2>/dev/null && \
     nc -z "$NODE_IP" "$MINIO_PORT" 2>/dev/null; then
    break
  fi
  echo -n "."
  sleep 0.5
done
echo " ready"

# ── Generate .env.dev ────────────────────────────────────────────────────
ENV_FILE="${PROJECT_DIR}/.env.dev"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by hack/dev-up.sh — do not edit manually.
# Worktree: ${WORKTREE}  |  Namespace: ${NS}
# Re-run 'just dev-up' to regenerate.

# --- Data stores (NodePort via cluster node — no port-forwards) ---
DATABASE_URL=postgres://platform:dev@${NODE_IP}:${PG_PORT}/platform_dev
VALKEY_URL=redis://:dev@${NODE_IP}:${VALKEY_PORT}
MINIO_ENDPOINT=https://${NODE_IP}:${MINIO_PORT}
MINIO_ACCESS_KEY=platform
MINIO_SECRET_KEY=devdevdev
MINIO_INSECURE=true

# --- Platform core ---
PLATFORM_LOG=debug,sqlx::query=warn,hyper=info
PLATFORM_LISTEN=0.0.0.0:${BACKEND_PORT}
PLATFORM_DEV=true
PLATFORM_ADMIN_PASSWORD=admin

# AES-256-GCM key for secrets encryption (64 hex chars = 32 bytes)
PLATFORM_MASTER_KEY=0000000000000000000000000000000000000000000000000000000000000000

# --- Container registry ---
# for image pull (localhost auto-allows plain HTTP; NodePort of DaemonSet registry proxy)
PLATFORM_REGISTRY_NODE_URL=localhost:${REGISTRY_NODE_PORT}
# for push (Kaniko --destination prefix; no scheme — Kaniko adds it)
PLATFORM_REGISTRY_URL=${PLATFORM_HOST}:${BACKEND_PORT}

# --- Agent/Pipeline pod communication ---
PLATFORM_API_URL=http://${PLATFORM_HOST}:${BACKEND_PORT}
PLATFORM_VALKEY_AGENT_HOST=valkey.${NS}.svc.cluster.local:6379
PLATFORM_VALKEY_PASSWORD=dev

# --- Namespace prefix (for per-project namespaces) ---
PLATFORM_NS_PREFIX=${NS}

# --- Storage paths (worktree-scoped) ---
PLATFORM_GIT_REPOS_PATH=/tmp/platform-e2e/${WORKTREE}/repos
PLATFORM_OPS_REPOS_PATH=/tmp/platform-e2e/${WORKTREE}/ops-repos

# --- Seed images (OCI tarballs imported into registry on startup, worktree-scoped) ---
PLATFORM_SEED_IMAGES_PATH=/tmp/platform-e2e/${WORKTREE}/seed-images

# --- Agent runner binaries (worktree-scoped) ---
PLATFORM_AGENT_RUNNER_DIR=/tmp/platform-e2e/${WORKTREE}/agent-runner

# --- Proxy binary (worktree-scoped, for pipeline/agent pod wrapping) ---
PLATFORM_PROXY_PATH=/tmp/platform-e2e/${WORKTREE}/proxy
PLATFORM_PROXY_BINARY_DIR=/tmp/platform-e2e/${WORKTREE}/proxy

# --- K8s config ---
KUBECONFIG=${KUBECONFIG_PATH}

# --- Preview proxy (host → cluster bridge for iframe previews) ---
PLATFORM_PREVIEW_PROXY_URL=http://${NODE_IP}:${PREVIEW_PROXY_PORT}

# --- WebAuthn / Passkeys ---
WEBAUTHN_RP_ID=localhost
WEBAUTHN_RP_ORIGIN=http://localhost:${BACKEND_PORT}
WEBAUTHN_RP_NAME=Platform

PLATFORM_MCP_SERVERS_TARBALL=/tmp/platform-e2e/${WORKTREE}/mcp-servers.tar.gz
PLATFORM_SEED_COMMANDS_PATH=${PROJECT_DIR}/seed-commands

# --- Mesh proxy injection ---
PLATFORM_MESH_ENABLED=true

# --- Gateway auto-deployment ---
PLATFORM_GATEWAY_AUTO_DEPLOY=true
PLATFORM_GATEWAY_NAMESPACE=${NS}
PLATFORM_GATEWAY_HTTP_NODE_PORT=${GATEWAY_HTTP_NODE_PORT}
PLATFORM_GATEWAY_TLS_NODE_PORT=${GATEWAY_TLS_NODE_PORT}
PLATFORM_GATEWAY_WATCH_NAMESPACES=${NS}

# --- Registry ---
# Stream blobs through the platform instead of redirecting to MinIO.
# Required in Kind — kaniko pods can't reach MinIO's NodePort directly.
REGISTRY_PROXY_BLOBS=true
EOF


# ── Summary ──────────────────────────────────────────────────────────────
echo ""
echo "==> Dev environment ready (${WORKTREE})"
echo "  Namespace:     ${NS}"
echo "  Postgres:      ${NODE_IP}:${PG_PORT}"
echo "  Valkey:        ${NODE_IP}:${VALKEY_PORT}"
echo "  MinIO:         ${NODE_IP}:${MINIO_PORT}"
echo "  Preview proxy: ${NODE_IP}:${PREVIEW_PROXY_PORT}"
echo "  Backend:       0.0.0.0:${BACKEND_PORT}"
echo "  Registry:      cluster node:${REGISTRY_NODE_PORT} → ${PLATFORM_HOST}:${BACKEND_PORT}"
echo "  .env.dev:      ${ENV_FILE}"
echo ""
echo "  Run: just dev"
echo "  Stop: just dev-down"
