apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    {{- if .Values.platform.ssh.enabled }}
    - name: ssh
      port: {{ .Values.platform.ssh.port }}
      targetPort: ssh
      protocol: TCP
    {{- end }}
  selector:
    {{- include "platform.selectorLabels" . | nindent 4 }}
